### PR TITLE
The First *Real* Bors PR.

### PR DESCRIPTION
**Pull request by vext01**
This change enables buildbot and bors-ng on this repo.

The `.buildbot.sh` script is called to run the build when bors is told to try or rollup.

The name of the script is under our control, so we can rename it if we want.

Please ask questions if you have any!

### CODE REVIEW

**Comment by vext01** [comment]
(I don't know why the build is marked as failed)

**Comment by vext01** [comment]
(There shouldn't be a build yet)

**Comment by ltratt** [comment]
Do you want to squash?

**Comment by vext01** [comment]
Why, I'm glad you asked, I most certainly do!

**Comment by ltratt** [comment]
Go ahead!

**Comment by vext01** [comment]
splat.

**Comment by ltratt** [comment]
bors try

**Comment by vext01** [comment]
bors delegate=ltratt

This should give you permission to do the `r+` later. We can add you to a list of admins who always have this permission.

**Comment by vext01** [comment]
that finished quicker than i expected.

**Comment by ltratt** [comment]
It doesn't look like it's run the tests?

**Comment by vext01** [comment]
Yeah, that's expected.

I've configured buildbot to run `.buildbot.sh`. This means that we can version control the CI steps themselves, and we don't have to change the buildbot config to make changes to the steps.

Anyway, the contents of the script currently are:
```
./x.py clean  # We don't clone afresh to save time and bandwidth.
RUST_BACKTRACE=1 ./x.py build --config .buildbot.toml --stage 1 -i src/libstd
```

So indeed, no testing is yet done.

We can turn them on if you like. I don't know what the outcome will be!

I'm not sure why the build is still orange. I'll check the configuration.

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors retry

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
splat

**Comment by vext01** [comment]
That last commit silences that particular error, but I'm going to do a full test run on bencher8 before we kick off bors again.

**Comment by vext01** [comment]
Sadly the tests fail in the same way as in #10:

```
...
thread '[run-pass] run-pass/backtrace-debuginfo.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3277:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
                                                                                 
---- [run-pass] run-pass/backtrace.rs stdout ----
                                                                                   
error: test compilation failed although it shouldn't!
status: signal: 6                                                                                                                                                                     
command: "/home/vext01/research/ykrustc_pv/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/vext01/research/ykrustc_pv/src/test/run-pass/backtrace.rs" "--target=x86_64-unknow$
-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/home/vext01/research/ykrustc_pv/build/x86_64-unknown-linux-gnu/test/run-pass/backtrace/a" "-Crpath" "$
O" "-Zunstable-options" "-Lnative=/home/vext01/research/ykrustc_pv/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-g" "-L" "/home/vext01/research/ykrustc_pv/build/x86_64-$
nknown-linux-gnu/test/run-pass/backtrace/auxiliary"                                                                                                                                   
stdout:                                                                                                                                                                               
------------------------------------------                                                                                                                                            
                                                                                                                                                                                      
------------------------------------------                                                                                                              
stderr:                                   
------------------------------------------                                                                                                                                            
rustc: /home/vext01/research/hsaingkai-llvm/include/llvm/CodeGen/SlotIndexes.h:418: llvm::SlotIndex llvm::SlotIndexes::getInstructionIndex(const llvm::MachineInstr&) const: Assertio$
 `itr != mi2iMap.end() && "Instruction not found in maps."' failed.                                                                                                                   
                                                                                                                                                                                      
------------------------------------------                                                                              

thread '[run-pass] run-pass/backtrace.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3277:9

---- [run-pass] run-pass/issues/issue-26484.rs stdout ----

error: test compilation failed although it shouldn't!
status: signal: 6
command: "/home/vext01/research/ykrustc_pv/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/vext01/research/ykrustc_pv/src/test/run-pass/issues/issue-26484.rs" "--target=x86_6
4-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/home/vext01/research/ykrustc_pv/build/x86_64-unknown-linux-gnu/test/run-pass/issues/issue-264
84/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/home/vext01/research/ykrustc_pv/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-g" "-L" "/home/vext01/research/ykrustc
_pv/build/x86_64-unknown-linux-gnu/test/run-pass/issues/issue-26484/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
rustc: /home/vext01/research/hsaingkai-llvm/include/llvm/CodeGen/SlotIndexes.h:418: llvm::SlotIndex llvm::SlotIndexes::getInstructionIndex(const llvm::MachineInstr&) const: Assertion
 `itr != mi2iMap.end() && "Instruction not found in maps."' failed.

------------------------------------------
```

At this stage, I have no idea what the error message is saying, but t's likely that my debug labels have broken some compiler assumptions.

Obviously I need to look into that, but what do you want to do with this PR in the meantime?

Cheers

**Comment by ltratt** [comment]
Do we have to turn debuglabels on to hit this error?

**Comment by vext01** [comment]
In the `config.toml`, I had `debuginfo = false`. The test suite is probably building some programs in debug mode.

**Comment by ltratt** [comment]
Ah, I see. I'm not sure. In one sense I wouldn't mind merging this, but there again, I feel like we shouldn't in general be merging something that breaks tests (at least until we understand for sure why they're failing). Do we think we can fix this test failure, or is it something we'll have to live with for a while?

**Comment by vext01** [comment]
> I feel like we shouldn't in general be merging something that breaks tests

To be clear, the code that broke the tests was already merged. We've just exposed the failure by running the tests.

> Do we think we can fix this test failure, or is it something we'll have to live with for a while?

Hard to say I'm afraid.

It frustrates me slightly that I'll be chasing LLVM again, when we know that in the long term we want to ditch it.

I suggest I investigate this today and see what I can come up with and report back.

In the meantime, it's up to you about this PR. We could:
 * Merge it turning off tests.
 * Leave it open in the hope that I can fix this soon.

I'm pretty torn myself.

**Comment by ltratt** [comment]
> To be clear, the code that broke the tests was already merged. We've just exposed the failure by running the tests.

Point taken. Let's merge this PR then investigate separately whether a) we're going to fix it or b) live with it until we can wean ourselves off LLVM.

[I assume that we thus need to disable bors from running tests?]

**Comment by vext01** [comment]
> [I assume that we thus need to disable bors from running tests?]

Yep.

By the way, were you happy with the concept and name of the `.buildbot.sh` script?

**Comment by ltratt** [comment]
Happy with both.

If you push a commit that disables tests, I expect we can get this done soon.

**Comment by vext01** [comment]
That should do it. Can I squash it in?

(I'll leave the style changes separate as they are nothing to do with CI per-se)

**Comment by ltratt** [comment]
Yep!

**Comment by vext01** [comment]
Squashed. You should be able to get bors to auto-merge this now.
